# Build options
[buildOptions]
optimizeWithTtx = false

# Building plans
# Sans
[buildPlans.Iosevkat]
family = "Iosevkat"
desc = "Default"
buildCharMap = true
snapshotFamily = 'Iosevkat'
snapshotFeature = {"NWID" = 0}
exportGlyphNames = true

[buildPlans.IosevkatTerm]
family = "Iosevkat Term"
spacing = "term"
snapshotFamily = 'Iosevkat'
snapshotFeature = {"NWID" = 1}
exportGlyphNames = true

[buildPlans.IosevkatFixed]
family = "Iosevkat Fixed"
spacing = "fixed"
snapshotFamily = 'Iosevkat'
snapshotFeature = {"NWID" = 1}
exportGlyphNames = true

# Slab
[buildPlans.IosevkatSlab]
family = "Iosevkat Slab"
desc = "Slab-serif"
buildCharMap = true
serifs = "slab"
snapshotFamily = 'Iosevkat Slab'
snapshotFeature = {"NWID" = 0}
exportGlyphNames = true

[buildPlans.IosevkatTermSlab]
family = "Iosevkat Term Slab"
serifs = "slab"
spacing = "term"
snapshotFamily = 'Iosevkat Slab'
snapshotFeature = {"NWID" = 1}
exportGlyphNames = true

[buildPlans.IosevkatFixedSlab]
family = "Iosevkat Fixed Slab"
serifs = "slab"
spacing = "fixed"
snapshotFamily = 'Iosevkat Slab'
snapshotFeature = {"NWID" = 1}
exportGlyphNames = true

# Curly
[buildPlans.IosevkatCurly]
family  = "Iosevkat Curly"
desc = "Curly Style"
snapshotFamily = 'Iosevkat'
snapshotFeature = {"ss20" = 1}
exportGlyphNames = true
[buildPlans.IosevkatCurly.variants]
inherits = "ss20"

[buildPlans.IosevkatTermCurly]
family  = "Iosevkat Term Curly"
spacing = "term"
snapshotFamily = 'Iosevkat'
snapshotFeature = {"NWID" = 1, "ss20" = 1}
exportGlyphNames = true
[buildPlans.IosevkatTermCurly.variants]
inherits = "ss20"

[buildPlans.IosevkatFixedCurly]
family  = "Iosevkat Fixed Curly"
spacing = "fixed"
snapshotFamily = 'Iosevkat'
snapshotFeature = {"NWID" = 1, "ss20" = 1}
exportGlyphNames = true
[buildPlans.IosevkatFixedCurly.variants]
inherits = "ss20"

# Curly Slab
[buildPlans.IosevkatCurlySlab]
family  = "Iosevkat Curly Slab"
desc = "Curly Style, Slab-serif"
serifs = "slab"
snapshotFamily = 'Iosevkat Slab'
snapshotFeature = {"ss20" = 1}
exportGlyphNames = true
[buildPlans.IosevkatCurlySlab.variants]
inherits = "ss20"

[buildPlans.IosevkatTermCurlySlab]
family  = "Iosevkat Term Curly Slab"
serifs = "slab"
spacing = "term"
snapshotFamily = 'Iosevkat Slab'
snapshotFeature = {"NWID" = 1, "ss20" = 1}
exportGlyphNames = true
[buildPlans.IosevkatTermCurlySlab.variants]
inherits = "ss20"

[buildPlans.IosevkatFixedCurlySlab]
family  = "Iosevkat Fixed Curly Slab"
serifs = "slab"
spacing = "fixed"
snapshotFamily = 'Iosevkat Slab'
snapshotFeature = {"NWID" = 1, "ss20" = 1}
exportGlyphNames = true
[buildPlans.IosevkatFixedCurlySlab.variants]
inherits = "ss20"

###################################################################################################
# Weight mappings (style => shape weight, menu weight, CSS weight)
#   Shape weight : affects the shape of the glyphs
#   Menu weight  : affects the font menu name
#   CSS weight   : affects the webfont CSS "font-weight" property
# IMPORTANT : Currently "menu" property only support 100, 200, 300, 350, 400, 450, 500, 600, 700,
#             800, 900, and "shape" properly only supports number between 100 and 900 (inclusive).

[weights.Thin]
shape = 100
menu  = 100
css   = 100

[weights.ExtraLight]
shape = 200
menu  = 200
css   = 200

[weights.Light]
shape = 300
menu  = 300
css   = 300

[weights.Regular]
shape = 400
menu  = 400
css   = 400

[weights.Medium]
shape = 500
menu  = 500
css   = 500

[weights.SemiBold]
shape = 600
menu  = 600
css   = 600

[weights.Bold]
shape = 700
menu  = 700
css   = 700

[weights.ExtraBold]
shape = 800
menu  = 800
css   = 800

[weights.Heavy]
shape = 900
menu  = 900
css   = 900

# slope mappings (style => slope angle, shape slope grade, menu slope, CSS slope)
[slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[slopes.Oblique]
angle = 9
shape = "oblique"
menu  = "oblique"
css   = "oblique"

[slopes.Italic]
angle = 9
shape = "italic"
menu  = "italic"
css   = "italic"

# Width mappings (style => shape width, menu width, CSS stretch)
#   Shape width   : affects the shape of the glyphs
#   Menu width    : affects the font menu name
#   CSS stretch   : affects the webfont CSS "font-stretch" property
#
# IMPORTANT : Currently "shape" property only support 3 ... 9
#              and "menu" only support 1 ... 9

[widths.Normal]
shape = 500
menu  = 5
css   = "normal"

[widths.Extended]
shape = 600
menu  = 7
css   = "expanded"
