[buildPlans.Iosevkat]
Jfamily = "Iosevkat"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.Iosevkat.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iosevkat.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Iosevkat.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Iosevkat.slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.Iosevkat.slopes.Oblique]
angle = 9
shape = "oblique"
menu  = "oblique"
css   = "oblique"

[buildPlans.Iosevkat.slopes.Italic]
angle = 9
shape = "italic"
menu  = "italic"
css   = "italic"
