[buildPlans.IosevkatTerm]
family = "Iosevkat Term"
spacing = "term"
exportGlyphNames = true
slopes.inherits = "default"

[buildPlans.IosevkatTerm.slopes.Oblique]
angle = 9
shape = "oblique"
menu  = "oblique"
css   = "oblique"

[buildPlans.IosevkatTerm.slopes.Italic]
angle = 9
shape = "italic"
menu  = "italic"
css   = "italic"
