[buildPlans.IosevkatTerm]
family = "Iosevkat Term"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkatTerm.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkatTerm.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkatTerm.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkatTerm.slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.IosevkatTerm.slopes.Oblique]
angle = 5
shape = "oblique"
menu  = "oblique"
css   = "oblique"

[buildPlans.IosevkatTerm.slopes.Italic]
angle = 5
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.IosevkatTerm.metricOverride]
powerlineShiftY = 100
